# run via: ansible-playbook --ask-vault-pass awsdestroy.yml --key-file ../awskey.pem
- hosts: localhost
  connection: local
  vars:
    region: us-east-1
    tagname: ansible_tower
  vars_files:
    - awskeys.yml
  tasks:
    - name: Gather EC2 facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Type": "{{ tagname }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2

    - name: Gather EC2 Database facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Type": ansible_database
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2db

    - name: Terminate EC2 Instance(s)
      ec2:
        instance_ids: '{{ item.instance_id }}'
        state: absent
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      with_items: 
        - "{{ ec2.instances }}"
        - "{{ ec2db.instances }}"  
