---
- name: Basic configuration of a test system
  hosts: localhost
  become: yes
  vars:
    debug: false
  tasks:
    - name: Ensure updates are applied
      package:
        name: "*"
        state: latest
      register: yum_results

    - name: debug based on yum_results
      debug:
        var: yum_results
      when: debug == true
    
    - name: debug based on variable for print
      debug:
        msg: "Debugging has been disabled. The debug variable is set to {{ debug }}"
      when: debug == false

      
