---
#### Make sure to run as 'ansible-playbook -u root -k' for first run
- name: Basic configuration of a test system
  hosts: kube03.lab
  become: yes
  roles:
    - dnskube
  tasks:
    - name: Create cgrimm user
      user:
        name: cgrimm
        state: present
        createhome: yes
        group: sudo
        append: yes

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      ignore_errors: true

    - name: Add authorized key for cgrimm
      authorized_key: 
        user: cgrimm
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Change the hostname to align with ansible hostname
      hostname:
        name= "{{ inventory_hostname }}"
      when:
        ansible_fqdn != ansible_ssh_host

    - name: Confirm apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure updates are applied
      package:
        name: "*"
        state: latest

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state: present
        dest: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        regexp: "^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != inventory_hostname



  
