---
#### Make sure to run as 'ansible-playbook -u root -k' for first run
- name: Basic configuration of a test system
  hosts: rhel8
  become: yes
  tasks:
    - name: Create cgrimm user
      user:
        name: cgrimm
        state: present
        createhome: yes
        group: wheel
        append: yes

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: Add authorized key for cgrimm
      authorized_key: 
        user: cgrimm
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub



  
