---
#### Make sure to run as 'ansible-playbook -u root -k' for first run
- name: Basic configuration of a test system
  hosts: rhel7.lab
  become: yes
  vars_files:
    - subvars.yml
  roles:
    - dns
  tasks:
    - name: Register with RHN Account
      redhat_subscription:
        state: present
        username: "{{ rhnusername }}"
        password: "{{ rhnpassword }}"
        auto_attach: true
    
    - name: Create cgrimm user
      user:
        name: cgrimm
        state: present
        createhome: yes
        group: wheel
        append: yes

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      ignore_errors: true

    - name: Add authorized key for cgrimm
      authorized_key: 
        user: cgrimm
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Ensure updates are applied
      package:
        name: "*"
        state: latest

    - name: Change the hostname to align with ansible hostname
      hostname:
        name= "{{ inventory_hostname }}"
      when:
        ansible_fqdn != ansible_ssh_host       
 
    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state: present
        dest: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        regexp: "^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != ansible_ssh_host


      
