---
#### Make sure to run as 'ansible-playbook -u root -k' for first run
- name: Basic configuration of a test system
  hosts: rhel8
  become: yes
  tasks:
    - name: Create cgrimm user
      user:
        name: cgrimm
        state: present
        createhome: yes
        group: wheel
        append: yes

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: Add authorized key for cgrimm
      authorized_key: 
        user: cgrimm
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Change the hostname to align with ansible hostname
      hostname:
        name="{{ inventory_hostname }}"
      when:
        ansible_fqdn != ansible_ssh_host

    - name: Ensure updates are applied
      package:
        name: "*"
        state: latest

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != inventory_hostname

    - name: Validate ansible_fqdn == inventory_hostname
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == inventory_hostname


  
