---
- name: Primary Testing Playbook
  hosts: target
  become: true
  tasks:
    - block:  
      - name: Install Packages
        yum:
          name: "{{ item }}"
          state: latest
        with_items:
          - httpd
          - firewalld

      - name: Start services
        service:
          name: "{{ item }}"
          state: started
          enabled: true
        with_items:
          - httpd
          - firewalld

      - name: Configure Firewalld to allow http
        firewalld:
          service: http
          port: 80/tcp
          state: enabled
          permanent: true
      
      rescue:
      - name: Create /var/www/html
        file:
          path: /var/www/html
          state: directory
         # owner: apache
         # group: apache
         # mode: 0644
         
      always:
      - name: Create indext file for /var/www/html
        template:
          src: ~/playbooks/templates/index.html.j2
          dest: /var/www/html/index.html
          # owner: apache
          # group: apache
          # mode: 0644

  

        
